training:
  batch_size: 256
  epochs: 5
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 0.0005

data:
  num_workers: 4
  train_data_path: data/cifar10
  test_data_path: data/cifar10

model:
  name: alexnet
  num_classes: 10

augmentation:
  use_augmentation: false
  random_crop: false
  random_horizontal_flip: false

logging:
  save_freq: 1
  log_dir: results/logs
  model_dir: results/models
